SCALER, VECTOR AND MATRICES AS PYTHON ARRAYS


Import relevant libraries

In [17]:
import numpy as np


In [18]:
#Declaring scalars, vectors and matrices

In [19]:
#Scalars

In [20]:
s = 5

In [21]:
s

5

In [22]:
#Vector

In [23]:
v = np.array([5,2,4])

In [24]:
v

array([5, 2, 4])

In [25]:
#By default V is ROW vector

In [26]:
#MATRICES

In [27]:
m = np.array([[5,12,6],[-3,0,14]])

In [28]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [30]:
#Data types: type(variable)

In [31]:
type(s)

int

In [32]:
type(v) #1 directionoal array

numpy.ndarray

In [33]:
type(m)

numpy.ndarray

In [34]:
#Shape(dimensions)

In [35]:
m.shape

(2, 3)

In [36]:
v.shape

(3,)

In [37]:
#Creating a column vector

In [38]:
v.reshape(1,3)

array([[5, 2, 4]])

In [39]:
v.shape

(3,)

In [40]:
v.reshape(3,1)

array([[5],
       [2],
       [4]])

In [41]:
v.shape

(3,)

In [43]:
#s.shape- it return an error because scalers ahs no shape

TENSORFLOW

In [44]:
#TENSORS:It works in aperculiar way. is the most general concept used to denote scaler vectors and matrices denoted as Rank 0, Rank 1, and Rank 2.

In [45]:
#Creating a Tensor

In [46]:
import numpy as np


In [48]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [51]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [52]:
t = np.array([m1,m2])

In [53]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [54]:
#Checking its shape

In [55]:
t.shape

(2, 2, 3)

In [56]:
#Manually creating a tensor

In [59]:
t_manual = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [60]:
t.shape

(2, 2, 3)

ADDITIONS AND SUBTRACTIONS

In [62]:
#1 conditing: The two matrices must have the same dimensions

In [63]:
m1 = np.array([[5,12,6],[-3,0,14]])

In [64]:
m2 = np.array([[9,8,7],[1,3,-5]])

In [65]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [66]:
t.shape

(2, 2, 3)

SUBTRACTION

In [81]:
a1 = np.array([[5,3],[-2,4]])

In [82]:
a2 = np.array([[7,-5],[3,8]])

In [83]:
a1-a2

array([[-2,  8],
       [-5, -4]])

SUBTRACTION &ADDITION OF VECTORS

In [89]:
b1 = np.array([1,2,3,4,5,6])
b2 = np.array([5,4,3,2,1,0])

In [90]:
b1 - b2

array([-4, -2,  0,  2,  4,  6])

In [91]:
b1.shape

(6,)

In [92]:
b1 + b2

array([6, 6, 6, 6, 6, 6])

# TRANSPOSE OF A MATRIX

In [1]:
import numpy as np

In [2]:
A = np.array([[5,12,6],[-3,0,14]])

In [4]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
#To transpose use : A.T

In [6]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [14]:
B = np.array([[2,8,9,7,6],[9,6,2,3,5]])

In [15]:
B

array([[2, 8, 9, 7, 6],
       [9, 6, 2, 3, 5]])

In [16]:
B.T

array([[2, 9],
       [8, 6],
       [9, 2],
       [7, 3],
       [6, 5]])

VECTOR MULTIPLICATION: They must be compatible

In [17]:
#The sum of the products with corresponding elements called DOT PRODUCTS

In [18]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [19]:
np.dot(x,y)

-66

In [20]:
# it is solved thus: 2*1 + 8*-7 + -4*3 = -68+2 = -66

DOT SCALAR

In [21]:
x

array([ 2,  8, -4])

In [22]:
5 * x

array([ 10,  40, -20])

SCALAR * MATRIX 

In [23]:
A = A = np.array([[5,12,6],[-3,0,14]])

In [24]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
3 * A

array([[15, 36, 18],
       [-9,  0, 42]])

MATRIX*MATRIX: Only an m x n and n x k matrices can be multiplied. e.g 2 x 3 can be multiplied by 3 x 1. 3 x 3, 3x 4. Also, 5 x 7 can be multiplied by 7 x 1, 7 x 2, 7x 7 etc. what is important is the second element must correspond with first element

LINEAR ALGEBRA USEFULNESS

1. Vectorized Code
2. Imgae recognition
3. Dimensionality reduction