In [1]:
#MULTIPLE LINEAR REGRESSION

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('1.02. Multiple linear regression.csv')

In [4]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [5]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [6]:
#DECLARE THE VARIABLES (Dependent and Indep)

In [7]:
from array import array

In [8]:
y = data[['SAT', 'Rand 1,2,3']].values.reshape(-1,2)
x = data['GPA'].values.reshape(-1,1)

In [9]:
y.shape

(84, 2)

In [10]:
#REGRESSION ITSELF

In [11]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [12]:
reg.coef_

array([[ 2.45217639e+02],
       [-1.45538617e-01]])

In [13]:
reg.intercept_

array([1028.64068603,    2.54420206])

In [14]:
reg.score(x,y)
#Reg Score returns the R-Squared of a linear regression.

0.2040703061816671

#ADJUSTED R SQUARE FORMULAR R*2

$𝑅^2_{𝑎𝑑𝑗.}=1−(1−𝑅^2)∗\frac{𝑛−1}{𝑛−𝑝−1}$



In [15]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.19436384650095584

FEATURE SELECTION MODULE FROM SKLEARN: AKA F_Regression, it creates simple linear regressions of each feature and the dependent variable. it help to gain improve speed and also help in removing teh variable that is not relevant.Recall if a variabe  has a value above 0.05% we can discard it. it calculate for each of the variables ...
it wll calclate GPA for SAT
and calculate GPA for Rand 1,2,3 in the above example


STANDADIZATION OR FEATURE SCALING: it is the process of transformimg the data into a standard scale. X-mean/SD. It make it easier to relate with the data. It allows us to force the data to appear the same

#Example
Data: Day 1 Exchange rate = 1.3, Daily Trading Volume = 110,000
Day 2 Exchange rate = 1.34 and Daily trading volume = 98,000
Day 3 Exchange rate = 1.25 and Daily trading volume = 135,000



To standardize : Mean = 1.3. sd = 0.045
Exchange rates = are transformed to 0.07, 0.96 and -1.03....Daily trade volumes  -0.25, -0.85 and 1.1 respectively
Standardized.

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
scaler.fit(x)

StandardScaler()

In [19]:
#We have to Transform the data

In [20]:
x_scaled = scaler.transform(x)

In [21]:
x_scaled

array([[-3.44538388],
       [-3.00093201],
       [-2.92685669],
       [-2.18610357],
       [-1.85276466],
       [-1.55646341],
       [-1.22312451],
       [-1.22312451],
       [-1.18608685],
       [-1.18608685],
       [-1.14904919],
       [-0.96386091],
       [-0.92682326],
       [-0.92682326],
       [-0.77867263],
       [-0.59348435],
       [-0.59348435],
       [-0.59348435],
       [-0.59348435],
       [-0.51940904],
       [-0.51940904],
       [-0.51940904],
       [-0.48237138],
       [-0.44533372],
       [-0.33422076],
       [-0.18607013],
       [-0.18607013],
       [-0.18607013],
       [-0.18607013],
       [-0.18607013],
       [-0.18607013],
       [-0.18607013],
       [-0.14903247],
       [-0.14903247],
       [-0.14903247],
       [-0.07495716],
       [-0.03791951],
       [ 0.03615581],
       [ 0.14726878],
       [ 0.14726878],
       [ 0.14726878],
       [ 0.18430643],
       [ 0.18430643],
       [ 0.22134409],
       [ 0.22134409],
       [ 0