In [1]:
#NUMPY

In [4]:
#Numpyis the fundamental package for numeric computing with python
#It provides powerful ways to create store and/or manipulate data which makes it able to seamlessly and speedily integrate with a wide variety of databases
#it is the basics for pandas, i.e pandas are built on this fundationwhich is a high perfirmance data centric package taht we will lean later in this course.

#Numpy array is similar to list, each element is associated with index. fixed in size lement is same type e.g integers
#accessible with integer and square bracket []
#it make it easier and afster to perform many computational operation using less memory
#e.g vector addition and subtraction

#a:array([0,1,2,3,4])
#type(a): numpy.ndarray
#numpy array can be sliced


In [5]:
#Numpy can be install on command prompt using: pip install numpy

In [6]:
#Advantages of NumPy Library
#A NumPy array has many advantages over regular Python lists. Some of them are
#isted below:
#1. NumPy arrays are much faster for insertion, deletion, updating, and reading
#2. NumPy arrays contain advanced broadcasting functionalities compared with
#Python arrays.
#3. NumPy array comes with a lot of methods that support advanced arithmetic
#linear algebra options.
#4. NumPy provides advanced multi-dimensional array slicing capabilities.
#In the next section, you will see how to create NumPy arrays using different
#methods


In [8]:
#Using Array Methods
#To create a NumPy array, you can pass a list to the array() method of the NumPy
#module as shown below:
#Script 1:
import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)

numpy.ndarray

In [9]:
#You can also create a multi-dimensional NumPy array. To do so, you need to create
#a list of lists where each internal list corresponds to the row in a 2-dimensional
#array. Here is an example of how to create a 2-dimensional array using the array()
#method.
#Script 2:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape

(3, 3)

In [10]:
#With the arrange () method, you can create a NumPy array that contains a range of
#integers. The first parameter to the arrange method is the lower bound, and the
#second parameter is the upper bound. The lower bound is included in the array.
#However, the upper bound is not included. The following script creates a NumPy
#array with integers 5 to 10.
#Script 3:
nums_arr = np.arange(5,11)
(nums_arr)

array([ 5,  6,  7,  8,  9, 10])

In [18]:
#SCRIPT4:
nums_arr = np.arange(60,71)
(nums_arr)


array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70])

In [20]:
nums_arr = np.arange(67,99)
(nums_arr)

array([67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [3]:
#You can also specify the step as a third parameter in the arrange() function. A step
#defines the distance between two consecutive points in the array. The following
#script creates a NumPy array from 5 to 11 with a step size of 2.
#Script:
import numpy as np
nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


In [4]:
#The ones() method can be used to create a NumPy array of all ones. Here is an
#example.
#Script:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [9]:
#ZERO ARRAYS

zeros_array = np.zeros((11,5))
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#Using Random Method
#The random.rand() function from the NumPy module can be used to create a
#NumPy array with uniform distribution.
#Script 10:
uniform_random = np.random.rand(4, 5)
print (uniform_random)


[[0.65923569 0.5699168  0.45565577 0.02770558 0.59487193]
 [0.00726328 0.04779449 0.8987292  0.8393236  0.56508705]
 [0.88961336 0.38143241 0.40761788 0.10599191 0.58755924]
 [0.79164453 0.78275703 0.30269002 0.25200756 0.87680496]]


In [12]:
##Finally, the random.randint() function from the NumPy module can be used to
#create a NumPy array with random integers between a certain range. The first
#parameter to the randint() function specifies the lower bound, the second
#parameter specifies the upper bound, while the last parameter specifies the number
#of random integers to generate between the range. The following example generates
#five random integers between 5 and 50.
#Script:
integer_random = np.random.randint(10, 50, 5)
print(integer_random)

[28 49 25 25 16]


In [13]:
#Reshaping NumPy Arrays
#A NumPy array can be reshaped using the reshape() function. It is important to
#mention that the product of the rows and columns in the reshaped array must be
#equal to the product of rows and columns in the original array. For instance, in the
#following example, the original array contains four rows and six columns, i.e., 4 x 6
#= 24. The reshaped array contains three rows and eight columns, i.e., 3 x 8 = 24.
#Script 13:
uniform_random = np.random.rand(4, 6)
uniform_random = uniform_random.reshape(3, 8)
print (uniform_random)


[[0.57047945 0.23336523 0.47776174 0.80836429 0.29938235 0.43146956
  0.02520444 0.35133412]
 [0.57661898 0.53003667 0.61840827 0.73577947 0.6160359  0.50191941
  0.77890126 0.87721262]
 [0.67806385 0.53869999 0.19894657 0.19262364 0.98578415 0.38844194
  0.0668844  0.55800974]]


In [14]:
#. Array Indexing And Slicing
#NumPy arrays can be indexed and sliced. Slicing an array means dividing an array
#into multiple parts.
#NumPy arrays are indexed just like normal lists. Indexes in NumPy arrays start
#from 0, which means that the first item of a NumPy array is stored at the 0th index.
#The following script creates a simple NumPy array of the first 10 positive integers.
#Script:
s = np.arange(1,11)
print (s)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
#To slice an array, you have to pass the lower index, followed by a colon and the
#upper index. The items from the lower index (inclusive) to the upper index
#(exclusive) will be filtered. The following script slices the array “s” from the 1
#st
#index to the 9th index. The elements from index 1 to 8 are printed in the output.
#Script:
print (s[1:9])

[2 3 4 5 6 7 8 9]


In [17]:
#if you specify only the upper bound, all the items from the first index to the upper
#bound are returned. similarly, if you specify only the lower bound, all the items
#from the lower bound to the last item of the array are returned.
#Script:
print (s[:5])
print (s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [18]:
#Array slicing can also be applied on a 2-dimensional array. To do so, you have to
#apply slicing on arrays and columns separately. A comma separates the rows and
#columns slicing. In the following script, the rows from the first and second index
#are returned, While all the columns returned. You can see the first two complete
#rows in the output.
#Script:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print (nums_2d[:2,:])

[[10 12 13]
 [45 32 16]]


In [19]:
#

In [20]:
#NumPy for Arithmetic Operations
#NumPy arrays provide a variety of functions to perform arithmetic operations.
#Some of these functions are explained in this section.
#3.5.1. Finding Square Roots
#The sqrt() function is used to find the square roots of all the elements in a list as
#shown below:
#Script:
nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print (np_sqr)


[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [21]:
#Finding Logs
#The log() function is used to find the logs of all the elements in a list as shown
#below:
#Script:
nums = [10,20,30,40,50]
np_log = np.log(nums)
print (np_log)


[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [22]:
#Finding Exponents
#The exp() function takes the exponents of all the elements in a list as shown below:
#Script:
nums = [10,20,30,40,50]
np_exp = np.exp(nums)
print (np_exp)


[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [23]:
#Finding Sine and Cosine
#You can find the sines and cosines of items in a list using the sine and cosine
#function, respectively, as shown in the following script.
#Script:
nums = [10,20,30,40,50]
np_sine = np.sin(nums)
print (np_sine)

nums = [10,20,30,40,50]
np_cos = np.cos(nums)
print (np_cos)


[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


In [24]:
#NumPy for Linear Algebra Operations
#Data science makes extensive use of linear algebra. The support for performing
#advanced linear algebra functions in a fast and efficient way makes NumPy one of
#the most routinely used libraries for data science. In this section, you will perform
#some of the most linear algebraic operations with NumPy.
#3.6.1. Finding Matrix Dot Product
#To find a matrix dot product, you can use the dot() function. To find the dot
#product, the number of columns in the first matrix must match the number of rows
#in the second matrix. Here is an example.
#Script:
A = np.random.randn(4,5)

B = np.random.randn(5,4)

Z = np.dot(A,B)

print (Z) 

[[-2.9686099   3.63142885 -0.35982842 -1.26719139]
 [ 0.44238719  3.54819428 -1.37924415 -1.70369811]
 [-0.96229558 -1.2141887   0.48907513  0.9072023 ]
 [-2.43264112  1.04615356 -0.31222838  0.58242381]]


In [25]:
#Element-wise Matrix Multiplication
#In addition to finding the dot product of two matrices, you can element-wise
#multiply two matrices. To do so, you can use the multiply() function. The
#dimensions of the two matrices must match.
#Script:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
multiply = np.multiply(nums_2d, nums_2d)
print (multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]
